language: generic
dist: xenial
sudo: required
addons:
  apt:
    update: true
    packages:
    - qemu-user-static
    - binfmt-support
services:
  - docker
install:
  # To use the qemu-arm-static in the docker container, host kernel should
  # enable the foreign architecture.
  - sudo apt update
  - sudo apt install -y qemu-user-static binfmt-support
  - update-binfmts --display
  - docker system info

script:
  - ./build.sh buster_rpi
before_deploy:
  - docker images
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
deploy:
  provider: script
  script: docker push nugulinux/buildenv:buster_rpi
  on:
    all_branches: true
