name: Docker publish - rootfs

on:
  push:

env:
  IMAGE_NAME: nugulinux/buildenv

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
          [
            noble_x64,
            noble_arm64,
            noble_armhf,
          ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Enable experimental feature
        run: |
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - name: Build image
        run: ./build.sh ${{ matrix.target }}
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish
        run: docker push $IMAGE_NAME:${{ matrix.target }}
