name: Manual
on:
  workflow_dispatch:
    inputs:
      comment:
        description: "Comment"
        required: false
        default: ""

env:
  IMAGE_NAME: nugulinux/buildenv:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Comment
        run: echo "Comment - ${{ github.event.inputs.comment }}"
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Enable experimental feature
        run: |
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - name: Build image
        run: docker build --squash -t $IMAGE_NAME .
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish
        run: docker push $IMAGE_NAME
