name: Manual
on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment'
        required: false
        default: ''

env:
  IMAGE_NAME: nugulinux/buildenv

jobs:
  build:
    runs-on: [ self-hosted, Linux, X64 ]
    strategy:
      fail-fast: true
      matrix:
        target: [xenial_x64, xenial_arm64, xenial_armhf, bionic_x64, bionic_arm64, bionic_armhf]
    steps:
    - name: Comment
      run: echo "Comment - ${{ github.event.inputs.comment }}"
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build image
      run: ./build.sh ${{ matrix.target }}
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish
      run: docker push $IMAGE_NAME:${{ matrix.target }}
